spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/testanimes"
    username: ${DB_USERNAME}
    password: ${WORK_DB_PASSWORD}

upload:
  path: "/C:/Users/svyatoslav.oprysko/Documents/spring/BackEndPart/uploads"